app/views/recipes/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, abort
from flask_login import login_required, current_user
from app.utilities.main import update_recipes_table, save_image, remove_old_image
from app.models import Recipe, Review
from app.forms import CommentForm, AddRecipeForm
from app import db
from sqlalchemy import func

recipes = Blueprint("recipes", __name__, template_folder="templates")


@recipes.route('/update-recipes')
@login_required
def update_recipes():
    """Checks for new recipes on the server. If found scrapes them and adds them to database"""
    if current_user.id != 1:
        abort(403)
    new_recipes_count = update_recipes_table()
    if new_recipes_count == 1:
        flash("1 new recipe has been added to the collection.")
    elif new_recipes_count != 0 and new_recipes_count > 1:
        flash(f"{new_recipes_count} new recipes have been added to the collection.")
    else:
        flash("No new recipes have been added to your database.")
    return redirect(url_for('main.index'))


@recipes.route('/search-results', methods=['GET', 'POST'])
def show_results():
    """Shows search results"""
    if request.method == 'POST':
        query = request.form.get('query')
    else:
        query = request.args.get('query')
    page = request.args.get('page', 1, type=int)
    per_page = 2

    if query:
        ingredients = query.split(' ')
        results = db.session.query(Recipe)
        for ingredient in ingredients:
            results = results.filter(Recipe.ingredients.contains(ingredient) | Recipe.category.contains(ingredient))
        results = results.all()
        search_results = db.session.query(
            Recipe, func.count(Review.rating).label('rating_count'), func.avg(Review.rating).label('avg_rating')).filter(
            Recipe.id.in_([recipe.id for recipe in results])).outerjoin(
            Review, Recipe.id == Review.recipe_id).group_by(Recipe.id).order_by(Recipe.id.desc()).paginate(page=page, per_page=per_page)
        total_pages = search_results.total // per_page
        if search_results.total % per_page != 0:
            total_pages += 1

        return render_template('recipes/search_results.html', query=query, recipes_data=search_results, per_page=per_page, total_pages=total_pages)
    else:
        return render_template('recipes/search_results.html', query=query)


@recipes.route('/recipe/<recipe_title>', methods=['GET', 'POST'])
def recipe(recipe_title):
    """Displays recipe"""
    form = CommentForm()
    recipe_id = request.args.get('recipe_id')
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.private:
        if current_user.is_anonymous or recipe.user_id != current_user.id:
            abort(403)

    recipe = db.session.query(Recipe, func.count(Review.rating).label('rating_count'), func.avg(Review.rating).label('avg_rating')).filter(
        Recipe.id == recipe_id).outerjoin(Review, Recipe.id == Review.recipe_id).group_by(Recipe.id).all()
    data = {
        'recipe': recipe[0],
        'ratings': Review.query.filter(Review.rating.isnot(None), Review.recipe_id == recipe_id).all(),
        'comments': Review.query.filter(Review.body.isnot(None), Review.recipe_id == recipe_id).order_by(Review.date_created.desc()).all()
    }

    if form.validate_on_submit():
        current_user.post_comment(form.body.data, recipe_id)
        return redirect(url_for('recipes.recipe', recipe_title=recipe_title, recipe_id=recipe_id))

    return render_template('recipes/recipe.html', data=data, comment_form=form)


@recipes.route('/submit-rating', methods=['POST'])
@login_required
def submit_rating():
    """Adds rating to database for the current recipe"""
    next_url = request.form.get('next_url')
    recipe_id = request.args.get('recipe_id')
    new_rating = int(request.form.get('rating'))
    recipe_id = Recipe.query.get_or_404(recipe_id).id
    current_user.submit_rating(new_rating, recipe_id)
    return redirect(next_url)


@recipes.route('/toggle-recipe-favourites', methods=['POST'])
@login_required
def toggle_favourite():
    """Toggles the recipe in the user's favourite recipes list"""
    next_url = request.form.get('next_url')
    recipe_id = request.args.get('recipe_id')
    current_user.toggle_favourite(recipe_id)
    return redirect(next_url)


@recipes.route('/favourite-recipes')
@login_required
def favourites():
    """Displays user's favourite recipes"""
    favourite_recipes = current_user.favourite_recipes
    return render_template('recipes/user_recipes.html', recipes=favourite_recipes, is_private=False)


@recipes.route('/user-recipes')
@login_required
def user_recipes():
    """Displays recipes created by current user"""
    added_recipes = current_user.added_recipes[::-1]
    return render_template('recipes/user_recipes.html', recipes=added_recipes, is_private=True)


@recipes.route('/add-recipe', methods=['GET', 'POST'])
@login_required
def add_recipe():
    """Adds new recipe to database"""
    form = AddRecipeForm()
    if form.validate_on_submit():
        if form.img_file.data:
            save_image(form.img_file.data)
        current_user.add_recipe(new_recipe=form.data)
        flash("Your recipe has been successfully added.")
        return redirect(url_for('recipes.user_recipes'))
    return render_template('recipes/add-recipe.html', form=form)


@recipes.route('/edit-recipe/<recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    """Edits recipe in database"""
    recipe_to_edit = Recipe.query.get_or_404(recipe_id)
    if current_user.is_anonymous or recipe_to_edit.user_id != current_user.id:
        abort(403)
    form = AddRecipeForm(data=recipe_to_edit.__dict__)
    if form.validate_on_submit():
        if form.img_file.data:
            remove_old_image(recipe_to_edit.img_filename)
            save_image(form.img_file.data)
            recipe_to_edit.img_filename = form.img_file.data.filename
        form.ingredients.data = form.ingredients.data.replace(',', ' | ')
        form.instructions.data = form.instructions.data.replace('.', ' | ')
        form.populate_obj(recipe_to_edit)
        db.session.commit()
        flash("Your recipe has been successfully edited.")
        return redirect(url_for('recipes.user_recipes'))
    return render_template('recipes/add-recipe.html', form=form)


@recipes.route('/delete-recipe/<recipe_id>')
@login_required
def delete_recipe(recipe_id):
    """Deletes recipe from database"""
    recipe_to_delete = Recipe.query.get_or_404(recipe_id)
    if current_user.is_anonymous or recipe_to_delete.user_id != current_user.id:
        abort(403)
    db.session.delete(recipe_to_delete)
    db.session.commit()
    return redirect(url_for('recipes.user_recipes'))



app/templates/recipes/add-recipe.html
{% extends 'base.html' %}
{% block content %}

    <div class="transparent-box">
        <h1 class="highlight">Add new recipe</h1>
        <!-- Add/Edit recipe form. -->
        <form method="post" action="" novalidate enctype="multipart/form-data">
            <div class="recipe-form">

            {{ form.hidden_tag() }}
            <p>
                {{ form.title.label }}<br>
                {{ form.title(class_="input-field", size=40) }}
                    {% for error in form.title.errors %}
                        <span class="form-error">{{ error }}</span>
                    {% endfor %}
            </p>

            <p>
                {{ form.category.label }}<br>
                {{ form.category(class_="input-field", size=40) }}
            </p>

            <p>
                {{ form.prep_time.label }}<br>
                {{ form.prep_time(class_="input-field", size=40) }}
            </p>

            <p>
                {{ form.cook_time.label }}<br>
                {{ form.cook_time(class_="input-field", size=40) }}
            </p>

            <p>
                {{ form.servings.label }}<br>
                {{ form.servings(class_="input-field", size=40) }}
            </p>

            <p>
                {{ form.ingredients.label }}<br>
                {{ form.ingredients(class_="input-field", rows="3", cols="50", placeholder="Comma separated ingredients.") }}
                {% for error in form.ingredients.errors %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>

            <p>
                {{ form.instructions.label }}<br>
                {{ form.instructions(class_="input-field", rows="3", cols="50") }}
                {% for error in form.instructions.errors %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>

            <p>
                {{ form.img_file.label }}<br>
                {{ form.img_file }}
                {% for error in form.img_file.errors %}
                    <span class="form-error">{{ error }}</span>
                {% endfor %}
            </p>

                {{ form.submit(class_="btn-elem btn btn-lg btn-dark") }}
                </div>

        </form>
    </div>
{% endblock %}

app/templates/recipes/search_results.html
{% extends "base.html" %}
{% block content %}
    <div class="search-results recipe-box">
        {% if recipes_data and recipes_data.items %}
            <h1 class="highlight">Found {{ recipes_data.total }} recipes with: {{ query }}</h1>
            <div class="separator"></div>

            <!-- Recipe cards -->
            <div class="cards row mx-auto">
                {% for item in recipes_data.items %}
                    {% set recipe = item[0] %}
                    {% set rating_count = item[1] %}
                    {% set avg_rating = item[2] if item[2] else 0 %}
                    <div class="card">
                        <a href="{{ url_for('recipes.recipe', recipe_title=recipe.title, recipe_id=recipe.id) }}">
                            <img src="{{ url_for('static', filename='images/' + recipe.img_filename) }}"
                                 class="card-img-top" alt="..."></a>

                        <div class="card-body">
                            <small class="muted-text uppercase small-block-size">{{ recipe.category }}</small>

                            <div class="truncate-title">
                                <a href="{{ url_for('recipes.recipe', recipe_title=recipe.title, recipe_id=recipe.id) }}"
                                   class="card-text" title="{{ recipe.title }}">{{ recipe.title }}</a>
                            </div>

                            <!-- Star buttons. -->
                            <div class="rating">
                                {% for n in range(1, 6) %}
                                    {% if n<=avg_rating %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="gold"
                                             class="bi bi-star-fill" viewBox="0 0 16 16">
                                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                        </svg>
                                    {% elif n - 1<avg_rating %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="gold"
                                             class="bi bi-star-half" viewBox="0 0 16 16">
                                            <path d="M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z"/>
                                        </svg>
                                    {% else %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="gold"
                                             class="bi bi-star" viewBox="0 0 16 16">
                                            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                        </svg>
                                    {% endif %}
                                {% endfor %}

                                {% if rating_count %}
                                    <small class="muted-text small-block-size">Rating: {{ avg_rating }}
                                        ({{ rating_count }} ratings)</small>
                                {% else %}
                                    <small class="muted-text small-block-size">No ratings yet.</small>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="nav-pages d-flex mx-auto">
                    {% if recipes_data.total / per_page > 1 %}
                        {% if recipes_data.page > 1 %}
                            <a class="btn btn-elem btn-secondary me-auto"
                               href="{{ url_for('recipes.show_results', query=query, page=recipes_data.page - 1) }}">&lt;&lt;Previous Page</a>
                        {% endif %}
                        {% if recipes_data.page + 1 <= total_pages %}
                            <a class="btn btn-elem btn-secondary ms-auto"
                               href="{{ url_for('recipes.show_results', query=query, page=recipes_data.page + 1) }}">Next Page&gt;&gt;</a>
                        {% endif %}
                    {% endif %}
            </div>
        {% elif not query %}
            <p class="search-feedback">You didn't provide any ingredient to search for.</p>
        {% else %}
            <p class="search-feedback">No matches for your search.</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/recipes/user_recipes.html
{% extends "base.html" %}
{% block content %}
     <!-- Flashed messages -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="ur-flashwrapper flashwrapper flashed-messages">
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        {% endwith %}

    <div class="transparent-box overflow-auto">
        {% if is_private %}
            <h1 class="highlight">My Recipes</h1>
        {% else %}
            <h1 class="highlight">Favourite recipes</h1>
        {% endif %}

        <div class="recipes-container">
            {% if recipes %}
            {% for recipe in recipes %}
                <!-- Recipe items -->
                <hr>
                <div class="recipe-item row">
                    <div class="col-lg-5 col-sm-5">
                        <a href="{{ url_for('recipes.recipe', recipe_title=recipe.title, recipe_id=recipe.id) }}">
                            <img class="recipe-img " src="{{ url_for('static', filename='images/' + recipe.img_filename) }}"
                             alt="A picture of {{ recipe.title }}">
                        </a>
                    </div>

                    <div class="user-recipe-title col-lg-7 col-sm-7">
                        <div class="truncate-title">
                            <a href="{{ url_for('recipes.recipe', recipe_title=recipe.title, recipe_id=recipe.id) }}"
                               title="{{ recipe.title }}">{{ recipe.title }}</a>
                        </div>

                        {% if is_private %}
                            <div class="group-buttons">
                                <a class="user-recipes-btn btn btn-lg btn-dark mt-2"
                                   href="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}">Edit</a>

                                <a class="btn-outline-dark user-recipes-btn btn btn-lg mt-2"
                                   href="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}">Delete</a>
                            </div>
                        {% else %}
                            <form method="post" action="{{ url_for('recipes.toggle_favourite', recipe_id=recipe.id) }}">
                                <button type="submit" class="user-recipes-btn btn btn-lg btn-secondary">Remove &#8722;
                                </button>
                                <input type="hidden" name="next_url" value="{{ url_for('recipes.favourites') }}">
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <p>No recipes.</p>
        {% endif %}
        </div>

        {% if is_private %}
            <hr>
            <!-- Add recipe button -->
            <a class="add-recipe-btn btn-elem btn btn-lg btn-secondary" href="{{ url_for('recipes.add_recipe') }}">Add Recipe
                &#43;
            </a>
        {% endif %}

    </div>
{% endblock %}