app/views/main/routes.py
from flask import Blueprint, render_template, session
from sqlalchemy import func
from app.utilities.main import get_categories
from app.models import Recipe, Review
from app import db

main = Blueprint("main", __name__, template_folder="templates")


@main.route('/')
@main.route('/home')
def index():
    """Displays homepage"""
    session['categories'] = get_categories()
    latest_recipes = db.session.query(
        Recipe, func.count(Review.rating).label('rating_count'), func.avg(Review.rating).label('avg_rating')).filter(
        Recipe.private.is_(False)).outerjoin(
        Review, Recipe.id == Review.recipe_id).group_by(Recipe.id).order_by(Recipe.id.desc()).limit(6).all()

    return render_template('index.html', recipes_data=latest_recipes)

app/views/recipes/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, abort
from flask_login import login_required, current_user
from app.utilities.main import update_recipes_table, save_image, remove_old_image
from app.models import Recipe, Review
from app.forms import CommentForm, AddRecipeForm
from app import db
from sqlalchemy import func

recipes = Blueprint("recipes", __name__, template_folder="templates")


@recipes.route('/update-recipes')
@login_required
def update_recipes():
    """Checks for new recipes on the server. If found scrapes them and adds them to database"""
    if current_user.id != 1:
        abort(403)
    new_recipes_count = update_recipes_table()
    if new_recipes_count == 1:
        flash("1 new recipe has been added to the collection.")
    elif new_recipes_count != 0 and new_recipes_count > 1:
        flash(f"{new_recipes_count} new recipes have been added to the collection.")
    else:
        flash("No new recipes have been added to your database.")
    return redirect(url_for('main.index'))


@recipes.route('/search-results', methods=['GET', 'POST'])
def show_results():
    """Shows search results"""
    if request.method == 'POST':
        query = request.form.get('query')
    else:
        query = request.args.get('query')
    page = request.args.get('page', 1, type=int)
    per_page = 2

    if query:
        ingredients = query.split(' ')
        results = db.session.query(Recipe)
        for ingredient in ingredients:
            results = results.filter(Recipe.ingredients.contains(ingredient) | Recipe.category.contains(ingredient))
        results = results.all()
        search_results = db.session.query(
            Recipe, func.count(Review.rating).label('rating_count'), func.avg(Review.rating).label('avg_rating')).filter(
            Recipe.id.in_([recipe.id for recipe in results])).outerjoin(
            Review, Recipe.id == Review.recipe_id).group_by(Recipe.id).order_by(Recipe.id.desc()).paginate(page=page, per_page=per_page)
        total_pages = search_results.total // per_page
        if search_results.total % per_page != 0:
            total_pages += 1

        return render_template('recipes/search_results.html', query=query, recipes_data=search_results, per_page=per_page, total_pages=total_pages)
    else:
        return render_template('recipes/search_results.html', query=query)


@recipes.route('/recipe/<recipe_title>', methods=['GET', 'POST'])
def recipe(recipe_title):
    """Displays recipe"""
    form = CommentForm()
    recipe_id = request.args.get('recipe_id')
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.private:
        if current_user.is_anonymous or recipe.user_id != current_user.id:
            abort(403)

    recipe = db.session.query(Recipe, func.count(Review.rating).label('rating_count'), func.avg(Review.rating).label('avg_rating')).filter(
        Recipe.id == recipe_id).outerjoin(Review, Recipe.id == Review.recipe_id).group_by(Recipe.id).all()
    data = {
        'recipe': recipe[0],
        'ratings': Review.query.filter(Review.rating.isnot(None), Review.recipe_id == recipe_id).all(),
        'comments': Review.query.filter(Review.body.isnot(None), Review.recipe_id == recipe_id).order_by(Review.date_created.desc()).all()
    }

    if form.validate_on_submit():
        current_user.post_comment(form.body.data, recipe_id)
        return redirect(url_for('recipes.recipe', recipe_title=recipe_title, recipe_id=recipe_id))

    return render_template('recipes/recipe.html', data=data, comment_form=form)


@recipes.route('/submit-rating', methods=['POST'])
@login_required
def submit_rating():
    """Adds rating to database for the current recipe"""
    next_url = request.form.get('next_url')
    recipe_id = request.args.get('recipe_id')
    new_rating = int(request.form.get('rating'))
    recipe_id = Recipe.query.get_or_404(recipe_id).id
    current_user.submit_rating(new_rating, recipe_id)
    return redirect(next_url)


@recipes.route('/toggle-recipe-favourites', methods=['POST'])
@login_required
def toggle_favourite():
    """Toggles the recipe in the user's favourite recipes list"""
    next_url = request.form.get('next_url')
    recipe_id = request.args.get('recipe_id')
    current_user.toggle_favourite(recipe_id)
    return redirect(next_url)


@recipes.route('/favourite-recipes')
@login_required
def favourites():
    """Displays user's favourite recipes"""
    favourite_recipes = current_user.favourite_recipes
    return render_template('recipes/user_recipes.html', recipes=favourite_recipes, is_private=False)


@recipes.route('/user-recipes')
@login_required
def user_recipes():
    """Displays recipes created by current user"""
    added_recipes = current_user.added_recipes[::-1]
    return render_template('recipes/user_recipes.html', recipes=added_recipes, is_private=True)


@recipes.route('/add-recipe', methods=['GET', 'POST'])
@login_required
def add_recipe():
    """Adds new recipe to database"""
    form = AddRecipeForm()
    if form.validate_on_submit():
        if form.img_file.data:
            save_image(form.img_file.data)
        current_user.add_recipe(new_recipe=form.data)
        flash("Your recipe has been successfully added.")
        return redirect(url_for('recipes.user_recipes'))
    return render_template('recipes/add-recipe.html', form=form)


@recipes.route('/edit-recipe/<recipe_id>', methods=['GET', 'POST'])
@login_required
def edit_recipe(recipe_id):
    """Edits recipe in database"""
    recipe_to_edit = Recipe.query.get_or_404(recipe_id)
    if current_user.is_anonymous or recipe_to_edit.user_id != current_user.id:
        abort(403)
    form = AddRecipeForm(data=recipe_to_edit.__dict__)
    if form.validate_on_submit():
        if form.img_file.data:
            remove_old_image(recipe_to_edit.img_filename)
            save_image(form.img_file.data)
            recipe_to_edit.img_filename = form.img_file.data.filename
        form.ingredients.data = form.ingredients.data.replace(',', ' | ')
        form.instructions.data = form.instructions.data.replace('.', ' | ')
        form.populate_obj(recipe_to_edit)
        db.session.commit()
        flash("Your recipe has been successfully edited.")
        return redirect(url_for('recipes.user_recipes'))
    return render_template('recipes/add-recipe.html', form=form)


@recipes.route('/delete-recipe/<recipe_id>')
@login_required
def delete_recipe(recipe_id):
    """Deletes recipe from database"""
    recipe_to_delete = Recipe.query.get_or_404(recipe_id)
    if current_user.is_anonymous or recipe_to_delete.user_id != current_user.id:
        abort(403)
    db.session.delete(recipe_to_delete)
    db.session.commit()
    return redirect(url_for('recipes.user_recipes'))



app/views/user/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, abort
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from app.forms import LoginForm, RegisterForm
from app import db
from app.models import User, Review

user = Blueprint("user", __name__, template_folder="templates")


@user.route('/register', methods=['GET', 'POST'])
def register():
    """Register user to database and logs in the user"""
    form = RegisterForm()
    if form.validate_on_submit():
        password = generate_password_hash(form.password.data, method='pbkdf2:sha256', salt_length=8)

        new_user = User(
            username=form.username.data,
            email=form.email.data,
            password=password,
        )
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user, remember=False)
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


@user.route('/login', methods=['GET', 'POST'])
def login():
    """Logs in the user"""
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('main.index'))
        else:
            flash("Login unsuccessful. Please check email and password.")
    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    """Redirects user to homepage after log out"""
    logout_user()
    return redirect(url_for('main.index'))


@user.route('/delete_comment', methods=['POST'])
@login_required
def delete_comment():
    """Deletes comment from database"""
    next_url = request.form.get('next_url')
    comment_id = request.args.get('comment_id')
    print(comment_id)
    comment_to_delete = Review.query.get_or_404(comment_id)
    if current_user.is_anonymous or comment_to_delete.user_id != current_user.id:
        abort(403)
    db.session.delete(comment_to_delete)
    db.session.commit()
    return redirect(next_url)


@user.route('/edit_comment', methods=['POST'])
@login_required
def edit_comment():
    """Edits comment in database"""
    next_url = request.form.get('next_url')
    comment_id = request.args.get('comment_id')
    comment_to_edit = Review.query.get_or_404(comment_id)
    if current_user.is_anonymous or comment_to_edit.user_id != current_user.id:
        abort(403)
    comment_to_edit.body = request.form.get('edited_comment')
    db.session.commit()
    return redirect(next_url)


app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <link rel="icon" href="{{ url_for("static", filename="images/icon.jpg") }}">
    <link rel="stylesheet" href="{{ url_for("static", filename="styles.css") }}">
    <title>Cook'd</title>
</head>
<body>
    <div class="container-fluid background-box">
        {% include 'navbar.html' %}

        {% block content %}{% endblock %}

        {% include 'footer.html' %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
</body>
</html>

app/templates/footer.html
<footer class="shadow" style="background-color: #64BDA7">
    <div class="footer-content mx-auto">
        <a href="{{ url_for('main.index') }}">
            <img class="logo" alt="logo" src="{{ url_for('static', filename='images/logo.jpg') }}"/>
        </a>
        <span style="color: aliceblue">Copyright &copy; 2023 Alexandra Ana</span>

        <!-- Social media icons -->
        <div class="footer-icons">
            <button>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white"
                     class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
            </button>

            <button>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white"
                     class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                </svg>
            </button>

            <button>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white"
                     class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                </svg>
            </button>
        </div>
    </div>
</footer>

app/templates/index.html
{% extends "base.html" %}
{% block content %}

     <!-- Flashed messages -->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="flashwrapper flashed-messages mx-auto">
{#                    <button type="button" onclick="close('flashed-messages')"><span aria-hidden="true">×</span></button>#}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endwith %}

    <!-- Homepage header -->
    <div class="index-header d-flex flex-column">
        <h1 class="big-header">Enjoy cooking?</h1>
        <h2>Get inspired by our variety of delicious recipes when you're out of ideas.</h2>
    </div>

    <div class="main-box">
        {% if recipes_data %}
            <h2>What's new</h2>
        {% endif %}

        <div class="cards row mx-auto">

            <!-- Recipe cards -->
            {% for item in recipes_data %}
                {% set recipe = item[0] %}
                {% set rating_count = item[1] %}
                {% set avg_rating = item[2] if item[2] else 0 %}
                <div class="card index-card">
                    <a href="{{ url_for('recipes.recipe', recipe_title=recipe.title, recipe_id=recipe.id) }}">
                        <img src="{{ url_for('static', filename='images/' + recipe.img_filename) }}"
                             class="card-img-top" alt="..."></a>

                    <div class="card-body">
                        <small class="recipe-category muted-text uppercase small-block-size">{{ recipe.category }}</small>
                        <div class="truncate-title">
                            <a href="{{ url_for('recipes.recipe', recipe_title=recipe.title, recipe_id=recipe.id) }}"
                               class="card-text" title="{{ recipe.title }}">{{ recipe.title }}</a>
                        </div>

                        <!-- Star buttons. -->
                        <div class="rating">
                            {% for n in range(1, 6) %}
                                {% if n<=avg_rating %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="gold"
                                         class="bi bi-star-fill" viewBox="0 0 16 16">
                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                    </svg>
                                {% elif n - 1<avg_rating %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="gold"
                                         class="bi bi-star-half" viewBox="0 0 16 16">
                                        <path d="M5.354 5.119 7.538.792A.516.516 0 0 1 8 .5c.183 0 .366.097.465.292l2.184 4.327 4.898.696A.537.537 0 0 1 16 6.32a.548.548 0 0 1-.17.445l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256a.52.52 0 0 1-.146.05c-.342.06-.668-.254-.6-.642l.83-4.73L.173 6.765a.55.55 0 0 1-.172-.403.58.58 0 0 1 .085-.302.513.513 0 0 1 .37-.245l4.898-.696zM8 12.027a.5.5 0 0 1 .232.056l3.686 1.894-.694-3.957a.565.565 0 0 1 .162-.505l2.907-2.77-4.052-.576a.525.525 0 0 1-.393-.288L8.001 2.223 8 2.226v9.8z"/>
                                    </svg>
                                {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="gold"
                                         class="bi bi-star" viewBox="0 0 16 16">
                                        <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                                    </svg>
                                {% endif %}
                            {% endfor %}

                            {% if rating_count %}
                                <small class="muted-text small-block-size">Rating: {{ avg_rating }} ({{ rating_count }}
                                    ratings)</small>
                            {% else %}
                                <small class="muted-text small-block-size">No ratings yet.</small>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


        <!-- Scrape recipes button only for admin account. -->

        {% if current_user.id == 1 %}
            <a class="btn btn-elem btn-lg btn-dark update-button mx-auto" href="{{ url_for('recipes.update_recipes') }}">Update
                recipes
                collection</a>
        {% endif %}
    </div>
{% endblock %}


app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid px-0">
        <!-- Navbar logo -->
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img class="logo" src="{{ url_for('static', filename='images/logo.jpg') }}" alt="">
        </a>

    <!-- Search form -->

        <form class="search-form-sm ms-auto me-5" action="{{ url_for('recipes.show_results') }}" method="post">
                <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
                <button class="btn btn-sm btn-outline-secondary" type="submit"></button>
            </form>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <!-- Recipe categories dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Categories
                    </a>

                    <form method="post" action="{{ url_for('recipes.show_results') }}">
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for category in session['categories'] %}
                                <li>
                                    <button class="dropdown-item btn-link text-decoration-none category-link"
                                            type="submit" name="query" value={{ category }}>{{ category }}</button>
                                </li>
                            {% endfor %}

                            {% if current_user.is_authenticated %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('recipes.user_recipes') }}">My Recipes</a>
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('recipes.favourites') }}">Favourites</a>
                                </li>
                            {% endif %}
                        </ul>
                    </form>
                </li>
            </ul>
        </div>

            <!-- Search form -->
            <form class="search-form-lg ms-auto me-5" action="{{ url_for('recipes.show_results') }}" method="post">
                <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
                <button class="btn btn-sm btn-outline-success" type="submit">Search</button>
            </form>

            <!-- User authentication -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav pl-5 my-2 my-lg-0">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout') }}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>